### ISSUE TITLE
[BUG]upload PBO cp file

### ISSUE THREAD

**Issue by Rubinator13** [Badminton-Apps/core#110]
# 🐞 bug report

### Affected Package

 The issue is caused by package @badvlasim/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Badvlasim Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by cskiwi** [comment]
File was misconfigured
